# species dictionary
species_dict = {
    0: {"species": "unknown", "abbreviation": "none"},
    1: {"species": "Pinus nigra", "abbreviation": "pini"},
    2: {"species": "Pinus sylvestris", "abbreviation": "pisy"},
    3: {"species": "Pinus strobus", "abbreviation": "pist"},
    4: {"species": "Betula pendula", "abbreviation": "bepe"},
    5: {"species": "Betula pubescens", "abbreviation": "bepu"},
    6: {"species": "Fagus sylvatica", "abbreviation": "fasy"},
    7: {"species": "Pseudotsuga menziesii", "abbreviation": "psme"},
    8: {"species": "Quercus rubra", "abbreviation": "quru"},
    9: {"species": "Quercus robur", "abbreviation": "quro"},
    10: {"species": "Quercus petraea", "abbreviation": "qupe"},
    11: {"species": "Carpinus betulus", "abbreviation": "cabe"},
    12: {"species": "Fraxinus excelsior", "abbreviation": "frex"},
    13: {"species": "Acer campestre", "abbreviation": "acca"},
    14: {"species": "Acer negundo", "abbreviation": "acne"},
    15: {"species": "Acer pseudoplatanus", "abbreviation": "acps"},
    16: {"species": "Acer platanoides", "abbreviation": "acpl"},
    17: {"species": "Abies alba", "abbreviation": "abal"},
    18: {"species": "Abies grandis", "abbreviation": "abgr"},
    19: {"species": "Sorbus torminalis", "abbreviation": "soto"},
    20: {"species": "Sorbus domestica", "abbreviation": "sodo"},
    21: {"species": "Sorbus aucuparia", "abbreviation": "soau"},
    22: {"species": "Ulmus glabra", "abbreviation": "ulgl"},
    23: {"species": "Ulmus minor", "abbreviation": "ulmi"},
    24: {"species": "Ulmus pumila", "abbreviation": "ulpu"},
    25: {"species": "Ulmus laevis", "abbreviation": "ulla"},
    26: {"species": "Tilia cordata", "abbreviation": "tico"},
    27: {"species": "Tilia platyphyllos", "abbreviation": "tipl"},
    28: {"species": "Larix kaempferi", "abbreviation": "laka"},
    29: {"species": "Larix decidua", "abbreviation": "lade"},
    30: {"species": "Alnus glutinosa", "abbreviation": "algl"},
    31: {"species": "Alnus incana", "abbreviation": "alin"},
    32: {"species": "Juglans nigra", "abbreviation": "juni"},
    33: {"species": "Ailanthus altissima", "abbreviation": "aial"},
    34: {"species": "Picea pungens", "abbreviation": "pipu"},
    35: {"species": "Picea sitchensis", "abbreviation": "pisi"},
    36: {"species": "Picea abies", "abbreviation": "piab"},
    37: {"species": "Rhus typhina", "abbreviation": "rhty"},
    38: {"species": "Taxus baccata", "abbreviation": "taba"},
    39: {"species": "Populus alba", "abbreviation": "poal"},
    40: {"species": "Populus nigra", "abbreviation": "poni"},
    41: {"species": "Populus × canadensis", "abbreviation": "none"},
    42: {"species": "Populus tremula", "abbreviation": "potr"},
    43: {"species": "Populus × canescens", "abbreviation": "none"},
    44: {"species": "Robinia pseudoacacia", "abbreviation": "rops"},
    45: {"species": "Prunus avium", "abbreviation": "prav"},
    46: {"species": "Salix caprea", "abbreviation": "saca"},
}
